FROM node:24.13.0-alpine

WORKDIR /app

COPY package.json package-lock.json turbo.json ./
COPY packages ./packages
COPY apps ./apps
COPY entrypoint.sh ./entrypoint.sh

RUN npm ci
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh", "worker"]