FROM node:24.13.0-alpine

WORKDIR /app

COPY package.json package-lock.json turbo.json ./
COPY packages ./packages
COPY apps ./apps

RUN npm ci

RUN npx prisma generate --schema=packages/db/prisma/schema.prisma

RUN npm run build --filter=worker

CMD ["npm", "run", "start", "--filter=worker"]
